title: Sustainable Software
description: Personal blog about software development and sustainability. I don't speak English as a native language, so please excuse my level.
theme: minima
logo: /assets/img/logo_linkedin.jpeg

header_pages:
  - index.md
  - about.md
  - posts.md

author: Daniel Caro
email: "[daniel.caro+github]@[gmail.com]"
linkedin_username: danielcarop
github_username:  danielcaro

disqus:
  shortname: danielcaro-github

# https://github.com/jekyll/minima/blob/v2.5.0/README.md
minima:
  include_styles: true

sass:
  style: compressed

# Markdown & plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Other collections
collections:
  posts:
    sort_by: date