title: Sustainable Software
description: Basic information about me,bal bala bla a lot de unrelevant info bla bla bla
theme: minima
logo: /assets/img/logo_linkedin.jpeg

header_pages:
  - about.md
  - posts.md
  - tutorials.md

author: Daniel Caro
email: "daniel.caro@gmail.com"
linkedin_username: danielcarop

# https://github.com/jekyll/minima/blob/v2.5.0/README.md
minima:
  include_styles: true

sass:
  style: compressed

# Markdown & plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Other collections
collections:
  tutorials:
    sort_by: date
  posts:
    sort_by: date